Repository chingu-voyages/geckos-project-16, pull requests merged in 2019-01, with the labels that each got.

#67 Style/disclaimer
  src/BlurredLoader.css
  src/BlurredLoader.js
  src/Disclaimer.js
  src/ImageShowCase.css
  src/ImageShowCase.js
  src/ImgWithPlaceholder.css
  src/ImgWithPlaceholder.js
  src/Routes.js
  src/ViewListingAction.js
  src/ViewListingContact.js
  src/ViewListingHolder.js
  src/ViewListingImages.js
  src/ViewListingInfo.js
  src/ViewListingPage.css
  src/ViewListingPage.js
  src/ViewListingStory.js
  src/ViewListingTitle.js
Labels: in progress

#69 Feature/search listings
  src/CardComponent.css
  src/CardComponent.js
  src/CardList.js
  src/FeaturedPosts.js
  src/LatestListings.js
  src/NavBar.js
  src/Routes.js
  src/ScrollToTop.css
  src/ScrollToTop.js
  src/SearchBox.css
  src/SearchBox.js
  src/ViewListingPage.css
  src/index.css
Labels: in progress

#72 Feature/search listings
  src/Footer.css
  src/Footer.js
  src/LatestListings.css
  src/LatestListings.js
  src/SearchBox.css
  src/SearchBox.js
  src/SearchBoxContent.js
  src/index.css
Labels: in progress

#73 Feature/search listings
  src/BlurredLoader.css
  src/CardList.js
  src/FeaturedPosts.css
  src/FeaturedPosts.js
  src/LatestListings.js
  src/Login.js
Labels: Design-related, enhancement, in progress

#78 Feature/listingpolicy
  public/pattern.svg
  src/ListingPolicy.css
  src/ListingPolicy.js
  src/index.css
Labels: in progress

#80 Refactor/signup
  src/FeaturedPosts.css
  src/Routes.js
  src/SignUp.css
  src/SignUp.js
  src/index.css
Labels: Design-related, done, enhancement, in progress

#85 Update index.css
  src/ListingPolicy.css
Labels: in progress

#82 Feature/seo
  package-lock.json
  package.json
  src/CardComponent.js
  src/Disclaimer.js
  src/Routes.js
  src/SignUp.js
  src/ViewListingImages.js
Labels: in progress

#88 Feature/error page
  public/error.svg
  src/ErrorNotFound.css
  src/ErrorNotFound.js
  src/Routes.js
Labels: in progress

#91 Feature/social media sharing
  src/Routes.js
  src/ViewListingContact.js
Labels: in progress

#93 Feature/create listing
  package-lock.json
  package.json
  semantic.json
Labels: in progress

#98 potential mobile solution
  src/components/containers/NavBar.js
  src/components/reusable/StyledContainer.css
Labels: in progress

#99 Feature/facebook login
  .env.development
  package-lock.json
  package.json
  src/components/dynamic/AuthHolder.css
  src/components/dynamic/AuthHolder.js
  src/components/dynamic/LogInForm.js
  src/index.css
Labels: in progress

#102 Feature/recaptcha
  package-lock.json
  package.json
  public/favicon.ico
  src/components/dynamic/AuthHolder.css
  src/components/dynamic/LogInForm.js
  src/components/dynamic/SignUpForm.js
  src/index.css
Labels: in progress

#103 Feature/google analytics
  .env.development
  package-lock.json
  package.json
  public/favicon.ico
  src/components/containers/NavBar.js
  src/components/dynamic/ListingForm.js
  src/components/dynamic/LogInForm.js
  src/components/dynamic/SignUpForm.js
  src/components/dynamic/ViewListingHolder.js
  src/helpers/analytics.js
Labels: in progress
